tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "sqlite"
brew "glib"
brew "cairo"
brew "cask"
brew "cmatrix"
brew "etcd", restart_service: true
brew "gobject-introspection"
brew "harfbuzz"
brew "libsndfile"
brew "ffmpeg"
brew "git"
brew "go"
brew "htop"
brew "ilmbase"
brew "libheif"
brew "openexr", link: false
brew "imagemagick"
brew "libuv"
brew "memcached", restart_service: true
brew "youtube-dl"
brew "mpv"
brew "mysql"
brew "neofetch"
brew "neovim"
brew "portaudio"
brew "postgresql", restart_service: true
brew "ranger"
brew "redis"
brew "sl"
brew "speedtest-cli"
brew "stockfish"
brew "tree"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "heroku/brew/heroku"
cask "db-browser-for-sqlite"
cask "iterm2"
cask "oracle-jdk"
cask "virtualbox"
